-- Creates/updates the merch table used by the admin panel.
-- Run this in Supabase SQL Editor.

create table if not exists public.merch (
  id bigint generated by default as identity primary key
);

alter table public.merch
  add column if not exists num text not null default '',
  add column if not exists name text not null default 'Merch Item',
  add column if not exists description text not null default '',
  add column if not exists status text not null default 'OUT OF STOCK',
  add column if not exists img text,
  add column if not exists image_file_name text,
  add column if not exists images text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists merch_num_idx on public.merch (num);

create or replace function public.set_merch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_merch_updated_at on public.merch;
create trigger trg_set_merch_updated_at
before update on public.merch
for each row
execute function public.set_merch_updated_at();

alter table public.merch enable row level security;

grant select on table public.merch to anon;
grant select, insert, update, delete on table public.merch to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'merch_id_seq'
  ) then
    grant usage, select on sequence public.merch_id_seq to authenticated;
  end if;
end
$$;

drop policy if exists "Public read merch" on public.merch;
create policy "Public read merch"
on public.merch
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated insert merch" on public.merch;
create policy "Authenticated insert merch"
on public.merch
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated update merch" on public.merch;
create policy "Authenticated update merch"
on public.merch
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated delete merch" on public.merch;
create policy "Authenticated delete merch"
on public.merch
for delete
to authenticated
using (true);
